tiki:
  outputs:
    dev:
      dbname: tiki_books
      host: "{{ env_var('POSTGRES_HOST') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      schema: analytics
      threads: 1
      type: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
  target: dev
